server:
  port: 8081

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/develbox
          jwk-set-uri: http://localhost:8083/auth/realms/develbox/protocol/openid-connect/certs

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: pass
    realmImportFile: develbox-realm.json